### ISSUE TITLE
Rename ourplcc/plcc docker image

### ISSUE THREAD

**Issue by StoneyJackson** [ourPLCC/plcc#13]
ourplcc/plcc doesn't actually run plcc, it really runs a bash shell in an environment that has plcc and its dependencies installed. So calling it plcc is disinformation.

So what's a better name?
- ourplcc/shell
- ourplcc/environment
- ourplcc/plcc-shell (java has jshell)
- ourplcc/plcc-bash (git has git-bash)

I think I'm liking plcc-bash. I'm open to other suggestions and feedback. So please send them! :)

**Comment by fosler** [comment]
Sorry for the empty message...

I'm not sure what you mean by "disinformation". PLCC is a tool SET, not a program. It depends on things in the Std directory, for example, and it contains a compiler-compiler whose name is plcc.py. The 'plcc' file is a script that invokes the plcc.py compiler-compiler, which is perfectly OK. I'm not sure what is the issue here, but it's clearly something to do with how docker users will thing of things. Since I'm not planning to use docker, feel free to organize docker-related things in a way that best meets your needs.

I'm worried that the docker-related organizational issues presented here overshadow the principal clarity of the PLCC tool set itself. But again, I don't plan on using docker at this point, so whatever organization works best for the docker users is fine with me.

**Comment by StoneyJackson** [comment]
Good points.

To make things more clear, maybe I should pull the Docker part out into a separate project under ourPLCC *and* give it a better name. That way it isn't confused with PLCC.

We still need to give the Docker-thing a better name.

Maybe PLCC-in-Docker. It's direct. It says what it is. The URL "path" in GitHub and DockerHub would be ourplcc/plcc-in-docker.

**Comment by fosler** [comment]
Separating the Docker part into a separate project is a good plan. The "PLCC-in-Docker" name is ideal.

**Comment by StoneyJackson** [comment]
🎉  https://github.com/ourPLCC/plcc-in-docker
