### ISSUE TITLE
The bats environment

### ISSUE THREAD

**Issue by jashelio** [ourPLCC/plcc#21]
The file tests.sh runs a shell via "/usr/bin/env bats". My computer cannot find the file "bats". Is that just something that was mistakenly left out of the repository?

**Comment by StoneyJackson** [comment]
bats is a 3rd party unit testing framework for bash. From PLCC's perspective, bats is a development dependency. That is, only developers of PLCC need bats installed. Also, PLCC would not distribute or maintain bats directly; just like PLCC wouldn't distribute or maintain Python or Java directly.

[bats-core's homepage](https://github.com/bats-core/bats-core) has instructions on how to install and use it. You can probably install it using your package-manager: e.g., `apt-get install bats`. This is probably the fast and dirty way to get it working for you.

Of course, you don't need to install it in your native environment. And you probably shouldn't, as then you have a potentially shared dependency across different projects you maintain; this is equivalent of using global variables, which can create dependency nightmares. Instead, it would be better to install those dependencies into a contained environment that only contains the dependencies needed to work on PLCC. I bet you know what comes next... Docker!

In the ./shell directory, I have specified a Docker container that contains all of the runtime dependencies of PLCC and now our single development dependency bats. Assuming Docker is installed and running on your machine, you can build the image for the container by running `./shell/build`. You can then run an instances of that image, called a container, by running `./shell/run`. If all goes well, you'll be at a bash prompt running inside the container. Now you can run the tests, `./tests.sh` .  `./shell/build` and `./shell/run` are small shell scripts that really just run docker-compose commands. These commands make use of `./shell/Dockerfile` (which defines the image) and `./shell/docker-compose.yml` (which defines how to build and run the container from the image).

Ultimately, this image, or some variant, will be used to set up automated testing (CI/CD) on GitHub. This is necessary so that GitHub knows how to install and run PLCC and its tests.
