### ISSUE TITLE
plcc crash should be a stack overflow RuntimeException?

### ISSUE THREAD

**Issue by jashelio** [ourPLCC/plcc#22]
Sometimes, when I run broken code, a plcc-generated interpreter fails instead of throwing an exception. Here is my example of the day. I ran this in Tim's SET interpreter. (It's supposed to demonstrate that you need pass-by-name semantics for this kind of code.)

$ rep
--> define until = proc( test, action )
                if test
                    then 9999
                    else { action; .until( test, action ) }

--> let x = 5 in { .until( zero?(x), set x = sub1( x ) ); x }
null
$

The exit status of the program was 1.

**Comment by StoneyJackson** [comment]
@fosler Any thoughts on this issue?

**Comment by fosler** [comment]
This issue can be fixed by using

     `System.err.println(e)`

instead of

     `System.out.println(e.getMessage())

in the `catch (Error e)` part of `ProcessFiles.java`.

I also noticed that in `ProcessFiles.java`, error messages were being sent to `System.out` instead of `System.err`. I have fixed these as well (on plcc.pithon.net). Feel free to push this as a minor fix.

**Comment by StoneyJackson** [comment]
All set.

**Comment by fosler** [comment]
Excellent! Good to have no more issues to deal with -- except master->main. Jim will be happy about this fix.
