### ISSUE TITLE
Incorrect error message for "arbno" grammar rule and separator token

### ISSUE THREAD

**Issue by jashelio** [ourPLCC/plcc#24]
It is illegal for the separator token in an arbno rule to be wrapped in angle brackets, i.e., saved for semantic analysis.
I understand the reasoning for this. (Although it could be nice if this restriction were removed. But not now.)
However, this is the error produced:

$ plccmk -c variables.plcc 
  26 [variables.plcc]: final separator in an arbno rule must be a Terminal
line: <decls> **= <decl> +<SEMI>

It makes it look like SEMI is not a Terminal, but it is; that's not the problem.

**Comment by StoneyJackson** [comment]
@jashelio Can you please post variables.plcc?

**Comment by fosler** [comment]
The error message should probably be something like this,with 'bare' added, so as not to confuse the one writing the grammar rule:

    final separator in an arbno rule must be a bare terminal

Maybe even use the word "Token" instead of "terminal", since "Token" appears most often in the class notes. I'm preparing a proposed new release of plcc.py (which deals with a small number of other things), and I'll take any suggestions about this into account before I submit the release for consideration by our group.

A comment on your semi-proposal to save the separator for semantics analysis:

Suppose you *could* save the separator tokens for semantic analysis. If there are n terms to be matched in the RHS and if n is positive, then the number of separator tokens would be n-1. What exactly would you *do* with them? Furthermore, there would be no separator tokens at all if the RHS were empty or just had one term. You would need to take this into account.

Assume you *want* to do something like this (which, as you know, PLCC will not accept):

    <foo> **= <thing> +<SEP>

You can achieve the same effect as follows (I have left off the annotated class names) in a way that PLCC will accept:

    <foo> ::= <thing> <morethings>
    <foo> ::=
    <morethings> **= <SEP> <thing>

In this way, if there is at least one <thing>, the <morethings> rule would give you a 'sepList' of separator tokens, one for each <thing> on the RHS of the <morethings> rule.

**Comment by jashelio** [comment]
I agree there is an easy workaround to capturing a separator token. And I have not yet come to a language grammar where I have needed it. This capturing feature is certainly not high priority, but were I to do it, I would say yes, make a list of those tokens that is size one less than the other item, even if that means it is empty.
[variables_plcc.txt](https://github.com/ourPLCC/plcc/files/5972821/variables_plcc.txt)

**Comment by StoneyJackson** [comment]
So where are we on this issue? Shall I close it accepting that the "easy workaround" is good enough? Or is this still and open request for a change? Or does this fall into "won't fix" (meaning since there is a reasonable work around, this feature isn't needed, so we don't have any intention to add it).

**Comment by fosler** [comment]
Close issue #24. The workaround is satisfactory, and I have never seen a case where even the workaround is needed. I suggest a "won't fix" resolution. The latest version of `plcc.py` throws an exception if the separator in a repeating rule is not a "bare Token", using that exact terminology in the error message.
