### ISSUE TITLE
feat(rep): Use rlwrap to enable command history

### ISSUE THREAD

**Issue by StoneyJackson** [ourPLCC/plcc#25]
@jashelio Based on the email you recently sent me...

I wonder if we the `rep` script could detect if rlwrap is available, and if it is use it to provide command history.

If we get this working for `rep`, we could generalize to other shells in PLCC.

On Windows, I'm not sure if this solution would work in DOS or PowerShell. However, it may work for MinGW and cygwin.

In Docker, we can ensure that the image has rlwrap installed, so this solution should work there.

**Comment by fosler** [comment]
I vote against this.

I have observed that the behavior of something like 'rlwrap java -cp Java Rep' in an interactive session is slightly different from leaving off the 'rlwrap' part. In particular, with 'rlwrap', the user input is echoed again on the next line before the input is passed on to Rep. (I can't see how to disable this feature.) This can be somewhat distracting, especially since the echoed input may be confused with program output that appears on the following line.

In V6, for example, consider the following input in language V6:
[ff.txt](https://github.com/ourPLCC/plcc/files/5989750/ff.txt)

When input to Rep, the output looks like this:

[ff.out.txt](https://github.com/ourPLCC/plcc/files/5989759/ff.out.txt)

When this is entered using the rlwrap font-end, the output which appears below looks confusing:

[rlff.out.txt](https://github.com/ourPLCC/plcc/files/5989763/rlff.out.txt)

I think it best if users are made aware of how to use rlwrap if they choose to do so. However, in the spirit of "KISS", I think it's a mistake to apply it automatically.

**Comment by jashelio** [comment]
Stoney,

As far as I know, rlwrap just intercepts stdio so it would be pretty hard to detect from inside the "bubble". (Unless using C and system calls)

For now I am just going to use it in class. I don't suggest we put it into the scripts, since we would have to ensure the system has that installed. Including it in the docker version is a fine idea, IMHO.

Jim

**Comment by StoneyJackson** [comment]
OK, this doesn't look good. I hadn't tried it. So thanks for pointing that out.

Wanting to try it, I just tried to install rlwrap inside the Docker container using Alpine's apk package manager. Failed. So at least for now, it doesn't look like I can easily install rlwrap just to make it available inside the container. So I think I'll leave this alone for now.

Thanks for all the input!

Closing this issue.
